let shopItemsData = [
  {
    id: "abc",
    name: "Casual Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/img-1.jpg",
  },
  {
    id: "def",
    name: "Office Shirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/img-2.jpg",
  },
  {
    id: "ghi",
    name: "T-Shirt",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/img-3.jpg",
  },
  {
    id: "jkl",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/img-4.jpg",
  },
  {
    id: "mno",
    name: "Mens Tie",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/img-5.png",
  },
  {
    id: "pqr",
    name: "Casual Shoes",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/img-6.png",
  },
  {
    id: "stu",
    name: "Black Suit",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/img-7.png",
  },
  {
    id: "vwx",
    name: "Polo Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/img-8.png",
  },
  {
    id: "yza",
    name: "Denim Shirt",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/img-9.png",
  },
  {
    id: "ada",
    name: "Denim pants",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/img-10.png",
  },
  {
    id: "eqr",
    name: "Black Cap",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/img-11.png",
  },
  {
    id: "hjh",
    name: "leather boots",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/images/img-12.png",
  },
];
